### ISSUE TITLE
Highest starred repo can be shown rather than recently updated repo

### ISSUE THREAD

**Issue by sumanth19k** [ieeessitvit/Tech-Updates#21]
When someone opens the website the recently edited repo is being highlighted, instead the highest starred repo should be seen first.

**Comment by dhairyaostwal** [comment]
@sumanth19k we can have another section for that as an achievement. But usually the aim of this project is to show the recently used repo. Your views?

**Comment by ssitvit** [comment]
Recently used repo can be under construction and people might not the website interesting anymore and the see more feature is not clicked until people really find the introduction as interesting.
