### ISSUE TITLE
Check CSS Mobile View

### ISSUE THREAD

**Issue by dhairyaostwal** [ieeessitvit/Tech-Updates#23]
@sandesh32 Check CSS mobile view especially social media icons

**Comment by Radhika14soni** [comment]
Hey, I'm a first time contributor and I would like to contribute. Any guidance would be appreciated. Thanks!

**Comment by ssitvit** [comment]
Hey, @Radhika14soni this project is in verge of completion. Please let us know your skills where we can contact you for further projects. Cheers!
